Prepare to rerun tests

diff --git a/.github/actions/test_ya/action.yml b/.github/actions/test_ya/action.yml
--- a/.github/actions/test_ya/action.yml
+++ b/.github/actions/test_ya/action.yml
@@ -117,72 +117,6 @@ runs:
         npm install -g @testmo/testmo-cli
     
 
-    - name: Upload tests result to testmo
-      id: th
-      if: inputs.testman_token && inputs.run_tests
-      shell: bash
-      env:
-        PR_NUMBER: ${{ github.event.number }}
-        TESTMO_TOKEN: ${{ inputs.testman_token }}
-      run: |
-        set -x
-        RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-        BRANCH_TAG="$GITHUB_REF_NAME"
-        ARCH="${{ runner.arch == 'X64' && 'x86-64' || runner.arch == 'ARM64' && 'arm64' || 'unknown' }}"
-        
-        case "$BUILD_PRESET" in
-          relwithdebinfo)
-            TESTMO_SOURCE="ya-${ARCH}"
-            ;;
-          debug)
-            TESTMO_SOURCE="ya-${ARCH}-debug"
-            ;;
-          release-*)
-            TESTMO_SOURCE="ya-${ARCH}-${BUILD_PRESET/release-/}"
-            ;;
-          *)
-            echo "Invalid preset: $BUILD_PRESET"
-            exit 1
-            ;;
-        esac
-        
-        case $GITHUB_EVENT_NAME in
-          workflow_dispatch)
-            TESTMO_RUN_NAME="${{ github.run_id }} manual"
-            EXTRA_TAG="manual"
-            ;;
-          pull_request | pull_request_target)
-            TESTMO_RUN_NAME="${{ github.run_id }} PR #${PR_NUMBER}"
-            EXTRA_TAG="pr"
-            BRANCH_TAG=""
-            ;;
-          schedule)
-            TESTMO_RUN_NAME="${{ github.run_id }} schedule"
-            EXTRA_TAG="schedule"
-            ;;
-          push)
-            TESTMO_RUN_NAME="${{ github.run_id }} POST"
-            EXTRA_TAG="post-commit"
-            ;;
-          *)
-            TESTMO_RUN_NAME="${{ github.run_id }}"
-            EXTRA_TAG=""
-            ;;
-        esac
-
-        testmo automation:resources:add-link --name build --url "$RUN_URL" --resources testmo.json
-        testmo automation:resources:add-field --name git-sha --type string --value "${GITHUB_SHA:0:7}" --resources testmo.json
-        RUN_ID=$(
-        testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{ inputs.testman_project_id }} \
-          --name "$TESTMO_RUN_NAME" --source "$TESTMO_SOURCE" --resources testmo.json \
-          --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"
-        )
-        echo "runid=${RUN_ID}" >> $GITHUB_OUTPUT
-        echo "TEST_HISTORY_URL=${TESTMO_URL}/automation/runs/view/${RUN_ID}" >> $GITHUB_ENV
-
-        # Print test history link
-        echo "10 [Test history](${TEST_HISTORY_URL})" >> $SUMMARY_LINKS
-
     - name: set environment variables required by some tests
       if: inputs.run_tests
       shell: bash
@@ -268,12 +202,15 @@ runs:
         ./ya --version
         
         echo "Build+Tests **{platform_name}-${BUILD_PRESET}** is running..." | GITHUB_TOKEN="${{ github.token }}" .github/scripts/tests/comment-pr.py
-        set +e
-        (./ya make ${{ inputs.build_target }} "${params[@]}" \
-          --stat --log-file "$YA_TEST_LOG_FILENAME" -DCONSISTENT_DEBUG \
+        
+        params+=(${{ inputs.build_target }} "${params[@]}" \
+          --stat -DCONSISTENT_DEBUG \
           --no-dir-outputs --test-failure-code 0 --build-all \
-          --cache-size 2TB --force-build-depends --evlog-file "$TMP_DIR/ya_evlog.jsonl" \
-          --junit "$JUNIT_REPORT_XML" --output "$OUT_DIR"; echo $? > exit_code) |& tee $TMP_DIR/ya_make.log
+          --cache-size 2TB --force-build-depends \
+          --output "$OUT_DIR")        
+        set +e
+        (./ya make "${params[@]}" --log-file "$YA_TEST_LOG_FILENAME" --evlog-file "$TMP_DIR/ya_evlog.jsonl" \
+          --junit "$JUNIT_REPORT_XML"; echo $? > exit_code) |& tee $TMP_DIR/ya_make.log
         set -e
         RC=`cat exit_code`
 
@@ -357,10 +294,68 @@ runs:
       if: inputs.testman_token && inputs.run_tests
       shell: bash
       env:
+        PR_NUMBER: ${{ github.event.number }}
         TESTMO_TOKEN: ${{ inputs.testman_token }}
       run: |
         set -x
         PROXY_ADDR=127.0.0.1:8888
+        
+        RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+        BRANCH_TAG="$GITHUB_REF_NAME"
+        ARCH="${{ runner.arch == 'X64' && 'x86-64' || runner.arch == 'ARM64' && 'arm64' || 'unknown' }}"
+        
+        case "$BUILD_PRESET" in
+          relwithdebinfo)
+            TESTMO_SOURCE="ya-${ARCH}"
+            ;;
+          debug)
+            TESTMO_SOURCE="ya-${ARCH}-debug"
+            ;;
+          release-*)
+            TESTMO_SOURCE="ya-${ARCH}-${BUILD_PRESET/release-/}"
+            ;;
+          *)
+            echo "Invalid preset: $BUILD_PRESET"
+            exit 1
+            ;;
+        esac
+        
+        case $GITHUB_EVENT_NAME in
+          workflow_dispatch)
+            TESTMO_RUN_NAME="${{ github.run_id }} manual"
+            EXTRA_TAG="manual"
+            ;;
+          pull_request | pull_request_target)
+            TESTMO_RUN_NAME="${{ github.run_id }} PR #${PR_NUMBER}"
+            EXTRA_TAG="pr"
+            BRANCH_TAG=""
+            ;;
+          schedule)
+            TESTMO_RUN_NAME="${{ github.run_id }} schedule"
+            EXTRA_TAG="schedule"
+            ;;
+          push)
+            TESTMO_RUN_NAME="${{ github.run_id }} POST"
+            EXTRA_TAG="post-commit"
+            ;;
+          *)
+            TESTMO_RUN_NAME="${{ github.run_id }}"
+            EXTRA_TAG=""
+            ;;
+        esac
+
+        testmo automation:resources:add-link --name build --url "$RUN_URL" --resources testmo.json
+        testmo automation:resources:add-field --name git-sha --type string --value "${GITHUB_SHA:0:7}" --resources testmo.json
+        RUN_ID=$(
+        testmo automation:run:create --instance "$TESTMO_URL" --project-id ${{ inputs.testman_project_id }} \
+          --name "$TESTMO_RUN_NAME" --source "$TESTMO_SOURCE" --resources testmo.json \
+          --tags "$BRANCH_TAG" --tags "$EXTRA_TAG"
+        )
+        echo "runid=${RUN_ID}" >> $GITHUB_OUTPUT
+        echo "TEST_HISTORY_URL=${TESTMO_URL}/automation/runs/view/${RUN_ID}" >> $GITHUB_ENV
+
+        # Print test history link
+        echo "10 [Test history](${TEST_HISTORY_URL})" >> $SUMMARY_LINKS
 
         openssl req -x509 -newkey rsa:2048 \
           -keyout $TMP_DIR/key.pem -out $TMP_DIR/cert.pem \
@@ -440,20 +435,10 @@ runs:
           echo "status=failed" >> $GITHUB_OUTPUT
         fi
 
-    - name: sync test results to s3
-      if: always() && inputs.run_tests
-      shell: bash
-      run: |
-        set -x
         echo "::group::s3-sync"
         s3cmd sync -r --follow-symlinks --acl-public --no-progress --stats --no-check-md5 "$ARTIFACTS_DIR/" "$S3_BUCKET_PATH/"
         s3cmd sync -r --follow-symlinks --acl-public --no-progress --stats --no-check-md5 "$TEST_ARTIFACTS_DIR/" "$S3_TEST_ARTIFACTS_BUCKET_PATH/"
         echo "::endgroup::"
-    
-    - name: check test results
-      if: inputs.run_tests
-      shell: bash
-      run: |
         .github/scripts/tests/fail-checker.py "$JUNIT_REPORT_XML"
 
     - name: show free space
